name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/deploy

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        make model-test
        make api-test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@main
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCP
      run: |
        gcloud builds submit --tag gcr.io/mlchallenge-79768/ml-challenge
        gcloud -q run deploy ml-challenge2 --image gcr.io/mlchallenge-79768/ml-challenge --platform managed --region us-central1 --allow-unauthenticated
